<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>false</UseWPF>
    <AssemblyName>MDviewer</AssemblyName>
    <RootNamespace>MDviewer</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>assets\app.ico</ApplicationIcon>
    <Version>1.4.0</Version>
    <BuildDate>$([System.DateTime]::Now.ToString("yyyy.MM.dd"))</BuildDate>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <AllowedReferenceRelatedFileExtensions>.pdb</AllowedReferenceRelatedFileExtensions>
    <DefaultItemExcludes>$(DefaultItemExcludes);setup_proj\**</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyMetadata Include="BuildDate" Value="$(BuildDate)" />
    <Compile Remove="setup_proj\**" />
    <EmbeddedResource Remove="setup_proj\**" />
    <None Remove="setup_proj\**" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="test-sample.md" LogicalName="MDviewer.test-sample.md" />
    <EmbeddedResource Include="diagram-sample.md" LogicalName="MDviewer.diagram-sample.md" />
    <EmbeddedResource Include="assets\logo.png" />
    <EmbeddedResource Include="assets\footer.png" />
    <EmbeddedResource Include="assets\app.ico" />
    <EmbeddedResource Include="assets\mermaid.min.js" />
    <EmbeddedResource Include="assets\SOGANG_UNIVERSITY_for_windows.ttf" />
    <EmbeddedResource Include="assets\albatross.png" />
    <EmbeddedResource Include="assets\campus.png" />
    <EmbeddedResource Include="assets\campus_light.png" />
    <EmbeddedResource Include="assets\assoc_guide.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Markdig" Version="0.41.3" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3351.48" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.3.0" />
  </ItemGroup>
  <Target Name="RemoveWebView2Wpf" BeforeTargets="ResolveAssemblyReferences">
    <ItemGroup>
      <ReferencePath Remove="@(ReferencePath)" Condition="'%(Filename)' == 'Microsoft.Web.WebView2.Wpf'" />
    </ItemGroup>
  </Target>
</Project>
